resolver: clash-1.4.6.yaml

extra-deps:
  - barbies-th-0.1.8
  - monoidal-containers-0.6.0.1

  - retroclash-lib-0.1.0
  - retroclash-sim-0.1.0
  - clash-shake-0.1.0
  - clashilator-0.1.0

packages:
  - clash-intel8080
  - .
