resolver: lts-13.24

packages:
  - location:
      git: https://github.com/gergoerdi/empty-clash
      commit: f5ce90ce1
    extra-dep: false

extra-deps:
#  - ghc-typelits-natnormalise-0.6.2
#  - ghc-typelits-knownnat-0.6
#  - ghc-typelits-extra-0.3.1
  - git: git@github.com:clash-lang/clash-compiler
    commit: 39d9dbf3fd71ed5c644a8a71f50dfbedfbd33b1f
    subdirs:
    - clash-prelude
    - clash-lib
    - clash-ghc

  - git: https://github.com/clash-lang/ghc-typelits-extra
    commit: 145a1a524d9ee163887e7da2edc11cd2ff977ab8
