resolver: lts-13.24

packages:
  - location:
      git: https://github.com/gergoerdi/empty-clash
      commit: f5ce90ce1
    extra-dep: false

extra-deps:
#  - ghc-typelits-natnormalise-0.6.2
#  - ghc-typelits-knownnat-0.6
#  - ghc-typelits-extra-0.3
  - git: git@github.com:clash-lang/clash-compiler
    commit: 9a466bd9c08b8ff8fc215bfbca318873e6d57e4a
    subdirs:
    - clash-prelude
    - clash-lib
    - clash-ghc

  - git: https://github.com/clash-lang/ghc-typelits-extra
    commit: a8de0b68b8216411cb862195354f251cd41bae50
