resolver: clash-HEAD.yaml
allow-newer: true

extra-deps:
  - barbies-th-0.1.8
  - monoidal-containers-0.6.0.1

packages:
  - clashilator
  - retroclash-lib
  - retroclash-sim
  - clash-shake

  - clash-intel8080

  - .
